## Create a Client to secure your first app

Keycloak Operator uses `KeycloakClient` Custom Resources to create and manage Client resources. You may create it by using the following command:

[source,bash]
----
$ kubectl create -f https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/latest/operator-examples/myclient.yaml
----

The above command will create a new Client within Keycloak Realm matched by `realmSelector`. The newly created Client will have an ID "client-secret".

Once the Client is created, check if it's ready:

[source,bash]
----
$ kubectl get keycloakclient/myclient -o jsonpath='{.status.ready}'
true
----

To make it easy for you we have a SPA testing application available on the https://www.keycloak.org/app/[Keycloak website].

ifeval::[{links-local}==true]
Open https://www.keycloak.org/app/ and click `Save` to use the default configuration.
endif::[]

ifeval::[{links-local}!=true]
Open https://www.keycloak.org/app/. Change `Keycloak URL` to the URL of your Keycloak instance. Click `Save`.
endif::[]

Now you can click `Sign in` to authenticate to this application using the Keycloak server you started earlier.
