:title: Introducing the Keycloak SRE special interest group
:date: 2024-09-03
:publish: true
:author: Michal Hajas, Alexander Schwartz

After an initial installation of Keycloak, users today spend a significant amount of time optimizing their installations, keeping them up to date and secure. When doing this, they follow the principles of Site Reliability Engineers, among others automation, setting service level objectives, keeping things simple and monitoring. As of today, Keycloak doesn’t provide much documentation and best practices in that area. The Keycloak project is also looking for faster feedback on changes so that we do not break existing installations without providing migration instructions on upgrades.

To improve the lives of people running and operating Keycloak, we’re starting the Site Reliability Engineers Special Interest Group, or SRE SIG for short. The idea is to speed up the feedback loop for existing and new features and to improve the communication between people operating Keycloak in real deployments and people developing Keycloak.

Desired outputs would include:

* Simplifying Keycloak’s configuration and upgrade process.
* Collecting best practices and feedback from real-world Keycloak installations to identify and prioritize new features.
* Educating users about what Keycloak can already do and what items are on the future roadmap.

== Topics to tackle

At the initial https://www.meetup.com/keycloak-hour-of-code/events/302619131/[meeting on August 19th 2024], we identified the following topics as initial discussion points to tackle by the group:

* How to load test Keycloak? +
(Introduction of keycloak-benchmark project, identifying possible enhancements and presenting custom community solutions)
* What are the right metrics of Keycloak to watch and how to visualize them in a dashboard?
* Can we simplify how Keycloak is configured and set up?

== Call to action
We have yet to decide what our regular meetings and cadence will look like, and we will discuss all the details in the Slack channel mentioned above. So stay tuned, join the https://cloud-native.slack.com/channels/keycloak-sre-sig[#keycloak-sre-sig Slack channel] and share your story with the group to better understand your needs and expectations!

== Communication channels

To receive the latest information about what is happening in the SIG join us in our https://cloud-native.slack.com/channels/keycloak-sre-sig[CNCF #keycloak-sre-sig Slack channel].
Use https://slack.cncf.io/ to join the CNCF Slack if you do not have an account yet.

For sharing documents and following the activities of SIG proceed to the https://github.com/keycloak/keycloak-sre-sig[keycloak/keycloak-sre-sig GitHub repository].
