:title: KeyConf24 program announced & livestream
:date: 2024-08-30
:publish: true
:author: Alexander Schwartz

KeyConf24, our 2024 Keycloak Identity Summit, will happen on September 19th, which is just around the corner! This year's event promises to be even bigger and better, with a program packed
full of relevant, cutting-edge topics.

This year due to high demand and limited space on-site, we're offering for the first time a live stream, so the Keycloak community can join remotely.

=== What to Expect at KeyConf24

The talks have been selected, and the program is now online at link:https://keyconf.dev/[].

Expect talks about:

* *European Digital Identity Wallet:* Deep dives into the European Union's ambitious initiative and its impact on identity management.

* *Verifiable Credentials:* Explore the exciting potential of decentralized identity verification and the role of Keycloak.

* *Real-world Keycloak integrations:* Technical sessions on Keycloak’s capabilities and how to leverage them in real world scenarios like the banking industry.

* *New and upcoming features in Keycloak:* Hear about the new organisations and user profile features which are available in the latest releases of Keycloak, as well as the next upcoming features.

=== Save the Date and join us in the live stream!

You can register for the live stream at link:https://keyconf.dev/[].

We're excited and are looking forward to meeting you at our event. Let's continue to shape the future of identity together!
