:title: Meet Keycloak at KubeCon EU, London in April 2025
:date: 2025-03-08
:publish: true
:author: Ryan Emerson
:preview: keycloak-kubecon-london-2025.png
:summary: We will be hosting a Kiosk in the Project Pavilion, as well as presenting a talk about Evolving OpenID Connect and Keycloak Observability. We are eager to meet Keycloak enthusiasts, users and newcomers alike.

We are thrilled to announce that Keycloak will be at KubeCon Europe, London April 1-4th 2025.

Keycloak's presence at previous KubeCons was a huge success, and we are always eager to meet Keycloak enthusiasts, users
and newcomers alike. At this year's event we will be hosting a Kiosk in the Project Pavilion, as well as presenting
a talk about Evolving OpenID Connect and Observability.

== Keycloak community Meet & Greet at the Project Pavilion

https://github.com/tnorimat[Takashi Norimatsu] from Hitachi, https://github.com/ryanemerson[Ryan Emerson] and https://github.com/mabartos[Martin Bartos]
from Red Hat, and other contributors will be hosting a Keycloak kiosk at the
https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/features-add-ons/project-engagement/#project-pavilion[Project Pavilion].
This is a great chance to meet people who use Keycloak, contribute to Keycloak, take our survey about new Keycloak features, and get some cool swag!

*Keycloak Kiosk opening hours:*

- Wednesday, April 2: 15:30 - 19:45
- Thursday, April 3: 14:00 - 17:00
- Friday, April 4: 12:30 - 14:00

== Presenting evolving OpenID Connect and Keycloak Observability

https://github.com/tnorimat[Takashi Norimatsu] and https://github.com/ryanemerson[Ryan Emerson] will be presenting a talk
on Evolving OpenID Connect and Observability in Keycloak.

- Friday, April 4, 14:30 - 15:00pm +
https://kccnceu2025.sched.com/event/1td1c/evolving-openid-connect-and-observability-in-keycloak-ryan-emerson-red-hat-takashi-norimatsu-hitachi?iframe=yes&w=100%&sidebar=yes&bg=no[*Evolving OpenID Connect and Observability in Keycloak*] +
By Takashi Norimatsu, Hitachi & Ryan Emerson, Red Hat.

== Related Talks

Keycloak has a powerful community in Japan, and we have received several contributions in the past. One of Keycloak's maintainers, Takashi Norimatsu, is based in Japan.
There is also a quite popular Japanese book about https://www.amazon.co.jp/dp/4865944362[Keycloak Authentication and Authorization] by Yoshiyuki Tabata that will soon appear in its second edition.

To learn more about community activities in Japan, join the following talk:

- Thursday April 3, 2025 14:15 - 14:45 +
https://kccnceu2025.sched.com/event/1txGx/cloud-native-communities-in-action-how-japan-shaped-its-path-to-kubecon-ota-kohei-apple-shu-muto-nec-solution-innovators-ltd-yuichi-nakamura-hitachi-ltd-sunyanan-choochotkaew-ibm-research-noriaki-fukuyasu-the-linux-foundntion[*Cloud Native Communities in Action: How Japan Shaped Its Path To KubeCon*] +
By Ota Kohei, Apple; Shu Muto, NEC Solution Innovators, Ltd.; Yuichi Nakamura, Hitachi, Ltd.; Sunyanan Choochotkaew, IBM Research; Noriaki Fukuyasu, The Linux Foundation

== See you soon!

We're preparing for KubeCon EU 2025 and can't wait to connect with our community. Mark your calendars and join us.

See you in London!