# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Setup JDK
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        distribution: temurin
        java-version: 17
        cache: maven

    - name: Check site links
      uses: ./.github/actions/linkcheck
      with:
        directory: ${{ github.workspace }}
        token: ${{ secrets.GITHUB_TOKEN }}
